apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-app
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-app
  template:
    metadata:
      labels:
        app: eshop-app
    spec:
      containers:
      - name: eshop-app
        image: <REGION>-docker.pkg.dev/<PROJECT_ID>/<REPO_NAME>/eshop:latest
        imagePullPolicy: IfNotPresent  # Use Always for CI/CD or production
        ports:
        - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        envFrom:
        - configMapRef:
            name: eshop-config
        - secretRef:
            name: eshop-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20 