apiVersion: v1
kind: Secret
metadata:
  name: eshop-secret
  namespace: eshop
type: Opaque
stringData:
  DB_USER: "user1"
  DB_PASSWORD: "root"
  DB_HOST: "<your-db-host>"
  DB_NAME: "<your-db-name>" 