name: CI/CD to GKE

on:
  workflow_run:
    workflows: ["Provision GCP Infra with Terraform"]
    types:
      - completed
#  push:
#    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  REPOSITORY: gke-docker-repo
  IMAGE: python-app
  CLUSTER_NAME: gke-cluster
  CLUSTER_LOCATION: us-central1
  DEPLOYMENT_NAME: python-app
  NAMESPACE: default
  IMAGE_PATH: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gke-docker-repo/python-app:latest

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pybuilder

    - name: Show key package versions
      run: |
        python --version
        pip show Flask
        pip show Werkzeug
        pip show pybuilder

    - name: Clean PyBuilder target directory
      run: rm -rf target

    - name: Run tests and generate coverage report
      run: |
        set -o pipefail
        COVERAGE_NO_WARNINGS=1 pyb clean analyze run_unit_tests 2>&1 | tee pyb.log
        status=${PIPESTATUS[0]}
        if [ $status -ne 0 ]; then
          echo "==== PyBuilder log ===="
          cat pyb.log
          echo "==== Coverage report ===="
          cat target/reports/coverage.xml || true
          exit $status
        fi
      # Shows coverage report on failure for easier debugging

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/reports/coverage.xml

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
        service_account: '${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_PATH .

    - name: Push Docker image
      run: |
        docker push $IMAGE_PATH

    - name: Wait for GKE cluster to be ready
      run: |
        for i in {1..10}; do
          if gcloud container clusters describe $CLUSTER_NAME --region $CLUSTER_LOCATION; then
            echo "Cluster is ready!"
            break
          else
            echo "Waiting for cluster to be ready..."
            sleep 30
          fi
        done

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_LOCATION
      
    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE_PATH -n $NAMESPACE
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE 