# Required GitHub Secrets:
#   GCP_PROJECT_ID: GCP project ID
#   WIF_PROVIDER: Workload Identity Federation provider resource name
#   SERVICE_ACCOUNT: Service account email to impersonate

name: Python application CI

on:
  workflow_run:
    workflows: ["Provision GCP Infra with Terraform"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  REGION: us-central1
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest test_app.py
    - name: Check coverage
      run: |
        pip install coverage
        coverage run --source=. -m unittest test_app.py
        coverage report -m 