name: CI/CD to GKE

on:
  workflow_run:
    workflows: ["Provision GCP Infra with Terraform"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
      GOOGLE_REGION: ${{ secrets.GCP_REGION }}
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
      # Cost-effective tip: Use 'terraform destroy' for unused resources and review plan before apply. 